# Mendefinisikan versi Kubernetes API yang digunakan
apiVersion: apps/v1

# Menentukan jenis object
kind: StatefulSet

# Menentukan informasi tentang object
metadata:
  name: mongo
  labels:
    app: karsajobs

# Menentukan spesifikasi yang diinginkan
spec:
  selector:
    matchLabels:
      app: karsajobs
      tier: data
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: karsajobs
        tier: data

    # Menentukan spesifikasi yang diinginkan
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:7.0
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /etc/mongo-credentials
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: config
          configMap:
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: secret
          secret:
            secretName: mongo-auth