apiVersion: v1  # Specifies the Kubernetes API version being used.
kind: Secret  # Defines that this is a Kubernetes Secret resource.
metadata:
  name: mongo-secret  # Specifies the name of the Secret resource.
  labels:
    app: mongo  # Assigns the 'mongo' label to this Secret resource.

data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # Base64 encoded value of the MongoDB root password.
  MONGO_ROOT_USERNAME: YWRtaW4=  # Base64 encoded value of the MongoDB root username.
